In [ ]:
import torch

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### **Set up the dataset**

**If the data has just come out of the SUMO simulation, we need to accumulate the warning according to vehicle and distance travelled.**

Run the following code to get ourput_*.csv

<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
   
    <vType id="Dangerous" minGap="1.00" maxSpeed="20.00" color="red" accel="4" decel="3" emergencyDecel="10" stepping="0.5" apparentDecel="3" tau="0.70" speedFactor="1.2" carFollowModel= "IDM"/>
    <vType id="Normal" minGap="2.5" maxSpeed="14.00" color="yellow" accel="2" decel="3" emergencyDecel="10" apparentDecel="3" stepping="0.25" tau="2.00" speedFactor="1.2" carFollowModel= "IDM"/>
    <vType id="Slow" minGap="2.50" maxSpeed="12.00" desiredMaxSpeed="10.00" color="blue" accel="1" decel="3" emergencyDecel="10" stepping="0.25" speedFactor="0.9" tau = "3.00" carFollowModel= "IDM"/>
    
</additional>

In [ ]:
import pandas as pd
import numpy as np

#This code groups the DataFrame by 'VehicleID' and iterates through each group separately, calculating the cumulative sum for each group.
def calculate_cumulative_total_per_vehicle(df):
     # Group by 'VehicleID' and iterate through groups
    for _, group_df in df.groupby('VehicleID'):
        cumulative_sum = 0

        for index, row in group_df.iterrows():
            cumulative_sum += row['Total']
            df.at[index, 'Total'] = cumulative_sum

    return df



def calculate_cumulative_total_per_vehicle(df, warning_features):
    result_df = df.copy()

    for warning in warning_features:
        # Group by 'VehicleID' and iterate through groups
        for _, group_df in df.groupby('VehicleID'):
            # Sort the group by 'Distance_driven' in descending order
            #group_df = group_df.sort_values(by='Distance_driven', ascending=False)


            # Calculate cumulative sum for the warning feature
            cumulative_sum = group_df[warning].cumsum()

            # Update the corresponding column in the result DataFrame
            result_df.loc[group_df.index, warning] = cumulative_sum

    return result_df


In [ ]:
# Example usage

dataset_800V_Warning = '/content/drive/MyDrive/Dataset_Driver_Behavior/Sumo_dataset_V1/800V_DS_Separated_worning_V2.csv'
dataset_800V_inVehicl= '/content/drive/MyDrive/Dataset_Driver_Behavior/Sumo_dataset_V1/800V_DS_Export_dataframe_V2.csv'


df_800V_Warning = pd.read_csv(dataset_800V_Warning) ## df
df_800V_inVehicl = pd.read_csv(dataset_800V_inVehicl) ## df1

#compute the total warning
columns_to_sum = ['Speed_respect', 'secure_dist', 'TTC_respect', 'safe_dist', 'Emergency_Brake']
to_Sum_Up = ['Speed_respect', 'secure_dist', 'TTC_respect', 'safe_dist', 'Emergency_Brake', 'Total']
df_800V_Warning['Total'] = df_800V_Warning[columns_to_sum].sum(axis=1)
df_800V_Warning = calculate_cumulative_total_per_vehicle (df_800V_Warning,to_Sum_Up)
df_800V_Warning['Distance_driven']=df_800V_Warning['Distance_driven'].astype(int)


df_800V_Warning.to_csv('/content/drive/MyDrive/Dataset_Driver_Behavior/Sumo_dataset_V1/Output_800V_DS_Separated_worning.csv', index=False)



dataset_1800V_Warning = '/content/drive/MyDrive/Dataset_Driver_Behavior/Sumo_dataset_V1/1800V_DS_Separated_worning_V1.csv'
dataset_1800V_inVehicl = '/content/drive/MyDrive/Dataset_Driver_Behavior/Sumo_dataset_V1/1800V_DS_Export_dataframe_V1.csv'

df_1800V_Warning = pd.read_csv(dataset_1800V_Warning)        ## Database2
df_1800V_inVehicl = pd.read_csv(dataset_1800V_inVehicl)  ## Database

#compute the total warning
columns_to_sum = ['Speed_respect', 'secure_dist', 'TTC_respect', 'safe_dist', 'Emergency_Brake']
to_Sum_Up = ['Speed_respect', 'secure_dist', 'TTC_respect', 'safe_dist', 'Emergency_Brake', 'Total']
df_1800V_Warning['Total'] = df_1800V_Warning[columns_to_sum].sum(axis=1)
df_1800V_Warning = calculate_cumulative_total_per_vehicle(df_1800V_Warning,to_Sum_Up )
df_1800V_Warning['Distance_driven']=df_1800V_Warning['Distance_driven'].astype(int)

df_1800V_Warning.to_csv('/content/drive/MyDrive/Dataset_Driver_Behavior/Sumo_dataset_V1/Output_1800V_DS_Separated_worning.csv', index=False)

df= df_1800V_Warning ################################


print(df_1800V_inVehicl.shape)
print(df_800V_Warning.shape)
print(df_800V_Warning)
print(df_1800V_inVehicl)

KeyboardInterrupt: 

**if we earledy accumulate the warning according to vehicle and distance travelled run this code**

In [ ]:
# Example usage

dataset_800V_Warning = '/content/drive/MyDrive/Dataset_Driver_Behavior/Sumo_dataset_V1/Output_800V_DS_Separated_worning.csv'
dataset_800V_inVehicl= '/content/drive/MyDrive/Dataset_Driver_Behavior/Sumo_dataset_V1/800V_DS_Export_dataframe_V2.csv'
df_800V_Warning = pd.read_csv(dataset_800V_Warning) ## df
df_800V_inVehicl = pd.read_csv(dataset_800V_inVehicl) ## df1



dataset_1800V_Warning = '/content/drive/MyDrive/Dataset_Driver_Behavior/Sumo_dataset_V1/Output_1800V_DS_Separated_worning.csv'
dataset_1800V_inVehicl = '/content/drive/MyDrive/Dataset_Driver_Behavior/Sumo_dataset_V1/1800V_DS_Export_dataframe_V1.csv'

#df = df.sort_values(by=[Label,'VehicleID','Total'],ascending=False)


df_1800V_Warning = pd.read_csv(dataset_1800V_Warning)        ## Database2
df_1800V_inVehicl = pd.read_csv(dataset_1800V_inVehicl)  ## Database

df= df_1800V_Warning ################################


print(df_1800V_Warning.shape)
print(df_800V_Warning.shape)
print(df_800V_Warning)
print(df_1800V_Warning)

(2101756, 11)
(916601, 11)
        Unnamed: 0    Step      Label VehicleID  Distance_driven  \
0                0     1.0     Normal   normal0                0   
1                1     2.0     Normal   normal0                1   
2                2     3.0     Normal   normal0                5   
3                3     4.0  Dangerous     dang0                0   
4                4     4.0     Normal   normal0               11   
...            ...     ...        ...       ...              ...   
916596      916596  4019.0       Slow   slow733             7299   
916597      916597  4020.0       Slow   slow733             7308   
916598      916598  4021.0       Slow   slow733             7318   
916599      916599  4022.0       Slow   slow733             7329   
916600      916600  4023.0       Slow   slow733             7339   

        Speed_respect  secure_dist  TTC_respect  safe_dist  Emergency_Brake  \
0                   0            0            0          0                0  


### **Grouper selon les steps**



In [ ]:


def Sum_x_step(df, features_to_keep ,features_to_sum,steps):

    # Round down the "Step" column to the nearest multiple of 5??????
    df["Step"] = df["Step"].apply(lambda n: ((n // steps) + 1) * steps)

    # Group by "VehicleID" and "Step" and calculate the sum for specified features
    features = features_to_sum
    #grouped_df = df.groupby(["VehicleID", "Step"])[features].sum()

    #grouped_df = df.groupby(["VehicleID", "Step"]).agg({"Distance_driven": "first", **{feature: "sum" for feature in features}})
    grouped_df = df.groupby(["VehicleID", "Step"]).agg({**{feature: "max" for feature in features_to_keep},
                                                        **{feature: "sum" for feature in features_to_sum}})



    return grouped_df

In [ ]:
Feature_to_sum= ['Speed_respect', 'secure_dist', 'TTC_respect', 'safe_dist', 'Emergency_Brake', "Total" ]
features = ['Distance_driven', 'Speed_respect', "secure_dist", "TTC_respect", "safe_dist", "Emergency_Brake", "Total"]
features_to_keep = ['Distance_driven', 'Label']

# Groupe df by 50 step
df =  Sum_x_step(df,features_to_keep, Feature_to_sum,50)


# Groupe df_800V_Warning by 50 step
df_800V_Warning =  Sum_x_step(df_800V_Warning,features_to_keep, Feature_to_sum,50)


print(df.shape)
print(df_800V_Warning.shape)
print(df_800V_Warning)
print(df)

(47629, 8)
(20472, 8)
                 Distance_driven      Label  Speed_respect  secure_dist  \
VehicleID Step                                                            
dang0     50.0               384  Dangerous             27          680   
          100.0              862  Dangerous             50         1811   
          150.0              937  Dangerous             50         2300   
          200.0             1288  Dangerous            445         2300   
          250.0             1976  Dangerous           1151         2300   
...                          ...        ...            ...          ...   
slow99    550.0             1160       Slow              0            0   
          600.0             1479       Slow              0            0   
          650.0             1863       Slow              0            0   
          700.0             2112       Slow              0            0   
          750.0             2565       Slow              0            0   

  

### **Preparation les donner pour ML algorithms**

In [ ]:
X = df[features]
Y = df['Label']



x= df_800V_Warning[features]
y = df_800V_Warning['Label']



X_train= X
X_test= x
y_train= Y
y_test = y


y_train.replace(['Slow', 'Normal','Dangerous'],[-1, 0, 1], inplace=True)
y_test.replace(['Slow', 'Normal','Dangerous'],[-1, 0, 1], inplace=True)

Loading the Iris dataset

### **GBDT classifier**


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
clf1 = GradientBoostingClassifier(n_estimators=10, learning_rate=1.0, max_depth=8,random_state=0)
clf1 = clf1.fit(X_train, y_train)

#print(X_train)
#print(y_test)
y_pred = clf1.predict(X_test)



print('Score, Training: ', clf1.score(X_train,y_train)) #accuracy score on training data
print('Score, Testing: ', clf1.score(X_test,y_test))

from sklearn.metrics import confusion_matrix


matrix = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(' The confusion matrix: ')
print(matrix)

Score, Training:  0.9303995464947826
Score, Testing:  0.8017780382962094
 The confusion matrix:  [[7532  426   13]
 [2603 3971  120]
 [ 100  796 4911]]


#### **KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import seaborn as sns

#Creating a NN classifier with K=3 and L1 distance (pour p=1)
knn = KNeighborsClassifier(n_neighbors=3)

#Fit tingour model
knn.fit(X_train, y_train)



KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred = knn.predict(X_test)

print('Score, Training: ', knn.score(X_train,y_train)) #accuracy score on training data
print('Score, Testing: ', knn.score(X_test,y_test))


# accuracy = accuracy_score(y_test, y_pred)
# print(y_test)

#print("Accuracy:", accuracy)
print(y_pred)
from sklearn.metrics import confusion_matrix

matrix = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(' The confusion matrix: ')
print(matrix)

Score, Training:  0.8948329799071993
Score, Testing:  0.7497557639703009
[ 1  1  1 ... -1 -1  0]
 The confusion matrix:  [[6458 1464   49]
 [2487 3970  237]
 [ 139  747 4921]]


### **MLP**

In [ ]:
from sklearn.neural_network import MLPClassifier
#https://analyticsindiamag.com/a-beginners-guide-to-scikit-learns-mlpclassifier/#:~:text=MLPClassifier%20stands%20for%20Multi%2Dlayer,perform%20the%20task%20of%20classification.


X_val = X_test
Y_val = y_test
#print(Y_val)



#Initializing the MLPClassifier
#classifierMLP = MLPClassifier(hidden_layer_sizes=(4,8,4), max_iter=3,activation = 'relu',solver='adam',random_state=1)
classifierMLP = MLPClassifier(hidden_layer_sizes=(4,8,4), max_iter=300, alpha=0.01, learning_rate_init=0.001, solver='adam', verbose=10,  random_state=21,tol=0.0000001)

#Fitting the training data to the network
classifierMLP.fit(X_train, y_train)


Iteration 1, loss = 4.43444841
Iteration 2, loss = 1.69449283
Iteration 3, loss = 1.09289223
Iteration 4, loss = 1.07142076
Iteration 5, loss = 1.05435546
Iteration 6, loss = 1.00161410
Iteration 7, loss = 1.00008233
Iteration 8, loss = 0.97573704
Iteration 9, loss = 0.89652826
Iteration 10, loss = 0.88888432
Iteration 11, loss = 0.90082575
Iteration 12, loss = 0.89112193
Iteration 13, loss = 0.85965020
Iteration 14, loss = 0.88261567
Iteration 15, loss = 0.83089086
Iteration 16, loss = 0.86005435
Iteration 17, loss = 0.84432753
Iteration 18, loss = 0.81814557
Iteration 19, loss = 0.81437256
Iteration 20, loss = 0.80661715
Iteration 21, loss = 0.78224927
Iteration 22, loss = 0.72963442
Iteration 23, loss = 0.77811924
Iteration 24, loss = 0.73672429
Iteration 25, loss = 0.75931563
Iteration 26, loss = 0.82944832
Iteration 27, loss = 0.74163535
Iteration 28, loss = 0.72861231
Iteration 29, loss = 0.70991211
Iteration 30, loss = 0.72693187
Iteration 31, loss = 0.69723803
Iteration 32, los

MLPClassifier(alpha=0.01, hidden_layer_sizes=(4, 8, 4), max_iter=300,
              random_state=21, tol=1e-07, verbose=10)

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
#Predicting y for X_val
X=0
y_pred = classifierMLP.predict(X_test)
# print(y_pred)
# print(y_pred.shape)
# print(y_test)


#print the value
# num_labels_to_print =1759
# for label in y_test:
#    i = 0
#    if label != y_pred [i]:
#         X+=1
#         i+=1
# print(X)


#Printing the accuracy
print(accuracy_score(y_test, y_pred))

#print(classifierMLP.score(X_val, Y_val))
print('Score, Training: ', classifierMLP.score(X_train,y_train)) #accuracy score on training data
print('Score, Testing: ', classifierMLP.score(X_val, Y_val))


matrix = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(' The confusion matrix: ')
print(matrix)

0.7905431809300508
Score, Training:  0.8466060593335992
Score, Testing:  0.7905431809300508
 The confusion matrix:  [[7683  288    0]
 [2966 3708   20]
 [ 146  868 4793]]


### **SVM classifier**


In [ ]:
#import SVC classifier
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

#Creating a SVM classifier with RBF Kernerl
svc_clf = make_pipeline(StandardScaler(), SGDClassifier(max_iter=1000, tol=1e-3))
# Fitting our model
svc_clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('sgdclassifier', SGDClassifier())])

In [ ]:
# Making predictions and calculate the Acc
predictions = svc_clf.predict(X_test)
# print(predictions)


print('Score, Training: ', svc_clf.score(X_train,y_train)) #accuracy score on training data
print('Score, Testing: ', svc_clf.score(X_test, y_test))


from sklearn.metrics import confusion_matrix

matrix = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(' The confusion matrix: ')
print(matrix)

Score, Training:  0.7810157677045497
Score, Testing:  0.7208382180539273
 The confusion matrix:  [[7683  288    0]
 [2966 3708   20]
 [ 146  868 4793]]
